name: CI Build Checks

on: [push, pull_request]

jobs:

  build-ubuntu-old:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Submodule checkout
      run: |
        git submodule update --init --recursive
    - name: make
      run: |
        make
    - name: Run unit tests
      run: |
        make unittests

  build-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodule checkout
      run: |
        git submodule update --init --recursive
    - name: make
      run: |
        make
    - name: Run unit tests
      run: |
        make unittests

  build-centos7:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        yum -y install git gcc make
    - name: Submodule checkout
      run: |
        git submodule update --init --recursive
    - name: make
      run: |
        make
    - name: Run unit tests
      run: |
        make unittests
